install:
- echo 'yes' | sudo add-apt-repository ppa:marutter/c2d4u
- echo 'yes' | sudo add-apt-repository ppa:texlive-backports/ppa
- sudo apt-get update
- sudo apt-get install graphviz texlive-latex-recommended texlive-latex-extra texlive-lang-swedish
  texlive-lang-finnish pandoc pandoc-citeproc
script:
- make dist/kandi.pdf dist/kandi.html
- "./deploy-gh-pages.sh"
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/Kauhsa/kandi.git
  - secure: KAzWje+qSBRz00UDD+TVGBFt00atlZoRguxkfmjshi6HGvZ7j3mMUV2kjnKRQ2LD5IpLiOU5NijPyo3+tF0peakB5L1aBhQgrgI4gtrkWMLT5Zen5ZoakuieW9DWSr5LdgPKACHBpGA3OPQ4L6JdQlhyj9I1KSP3nQbhlY9qIWs=
